// Please include this preamble in every page!
:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Further Information

== VS Code Extension Pack
The https://github.com/devonfw/extension-pack-vscode[devonfw Platform Extension Pack] is a collection of useful extensions for Visual Studio Code that support the development of devonfw applications. You can get it https://marketplace.visualstudio.com/items?itemName=devonfw.devonfw-extension-pack[here].

[NOTE]
====
Please be aware that the Extension Pack is quite 'extensive' and will take a while to download and install. It might also slow down VS Code depending on your system. To avoid this you can take a look at the included https://github.com/devonfw/extension-pack-vscode/blob/master/README.md[extensions] and install them individually if needed.
====

== SonarQube Plug-in (Architecture Validation)
The https://github.com/devonfw/sonar-devon-plugin[devon plug-in] for SonarQube can be used to validate if a certain project follows the devonfw architecture blueprint. Please refer to the https://github.com/devonfw/sonar-devon-plugin/wiki/guide-sonar-qube-setup[setup] guide in the respective repository, if you want to start using this plug-in.

== MrChecker Framework (E2E Testing)
The https://github.com/devonfw/devonfw-testing[MrChecker] framework for end-to-end testing is supplied in the form of a Maven project which you can extend with your own test cases. It supports the classic JUnit, as well as the Cucumber test structure. Please visit the MrChecker https://github.com/devonfw/devonfw-testing/wiki[wiki] to learn more.

ifdef::env-github[]
'''
*You did it!* This is the final page of the _devonfw getting started guide_. +
We reccomend, you bookmark links you found useful during reading in your browser.
endif::[]