:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Personas

Our target audience for this guide covers a wide variety of users, such as students -- who are still studying and want to work in the industry in the future, new software engineers -- who have completed their education and just started working in the industry, senior software engineers -- who already have severaly years of industry experience, and architects -- who have a vast amount of experience and are now leading teams and interacting with customers directly.

To provide an entry point for all these users, we have to group them by level of experience. We do this by introducing three personas, which represent our most common user groups.

These personas are called:

* *Junior Engineer*
* *Senior Engineer*
* *Architect*

In the link:guide-getting-started-introduction.asciidoc[introduction] we have already covered topics that concern all our users. Now *you* -- the reader -- have to evaluate which persona best fits your personal level of experience and follow the guide accordingly.

== Our Goals

Provide *Junior Engineers* with:

* simple-to-follow, result-oriented tutorials for key technologies (Java, Angular)
* introductory courses on more specialized development topics (Node.js)

Provide *Senior Engineers* with:

* advanced devonfw tools and the documentation to use them
* in-depth devonfw technical documentation

Provide *Architects* with:

* devonfw application and architecture design guidelines


ifdef::env-github[]
'''
*Next Step:*
link:guide-persona-junior-engineer.asciidoc[for Junior Engineers] |
link:guide-persona-senior-engineer.asciidoc[for Senior Engineers] |
link:guide-persona-architect.asciidoc[for Architects]
endif::[]