// Please include this preamble in every page!
:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Home
The following pages will guide you in your inital discovery of the *devon framework* (often abbreviated "devonfw" and referred to as "devon").

TIP: Just follow the link at the bottom of this and each subsequent page to visit the listed pages in their intended order.

== Resource Overview
You will find a collection and short descriptions of the major devonfw resources link:overview.asciidoc[here].

== Framework Introduction
If don't quite know what devon is all about yet, you will find a short introduction to the framework, its core ideas and the software stack behind it link:introduction.asciidoc[here].

== IDE Setup
If you want to start working with devon, you'll have to set up the development environment on your system first, which is explained link:ide.asciidoc[here].

== JumpTheQueue Tutorial App
link:jumpthequeue.asciidoc[JumpTheQueue] is a small application, which you can build yourself by following a step-by-step tutorial. This will teach you more about the components, layers and workflow of devon.

== MyThaiStar Sample App
link:mythaistar.asciidoc[MyThaiStar] is a more complex sample app, that demonstrates the full capabilities of the devon stack and framework.

== Further Information
You can find links to advanced devon topics and other resources closely related to the devon framework link:further-information.asciidoc[here].

'''

*First Step:* link:overview.asciidoc[Resource Overview]