// Please include this preamble in every page!
:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Home
The following pages are meant to guide you in your inital discovery of the *devon framework* (often abbreviated "devonfw" and referred to as "devon").

== link:overview.asciidoc[Resource Overview]
Here you will find a collection of the major devonfw resources.

== link:introduction.asciidoc[Framework Introduction]
If don't quite know what devon is all about yet, you will find a short introduction to the framework, its core ideas and the software stack behind it here.

== link:ide.asciidoc[IDE Setup]
If you want to start working with devon, you'll have to set up the development environment on your system first, which is explained here.

== link:jumpthequeue.asciidoc[JumpTheQueue Tutorial App]
JumpTheQueue is a small devon application, which you can build yourself by following a step-by-step tutorial. This will teach you more about the components, layers and workflow of devon.

== link:mythaistar.asciidoc[MyThaiStar Sample App]
MyThaiStar is a more complex sample app, that demonstrates the full capabilities of the devon stack and framework.

== link:further-information.asciidoc[Further Information]
Here you can find links to advanced devon topics and other resources closely related to the devon framework.