// Please include this preamble in every page!
:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= The devon IDE
First we have to clarify what we are talking about, when we mention the *devon IDE*:

The devon IDE is *not* one monolithic program that is installed with a traditional executable; rather it's a collection of scripts which are invoked via command line to automate several, repetetive development tasks. These scripts then interact with other tools (e.g. link:https://maven.apache.org/[Maven], link:https://jenkins.io/[Jenkins]), frameworks (link:https://spring.io/[Spring], link:https://angular.io/[Angular]) or third party IDEs (link:https://www.eclipse.org/downloads/[Eclipse], link:https://code.visualstudio.com/download[VS Code], link:https://www.jetbrains.com/idea/download/[IntelliJ IDEA]) to streamline the development workflow. +
As such, the package size of the IDE is initally very small, the setup is simple, the included software is portable and the whole environment is unobtrusive and light on system resources.

== Setup
Please refer to the link:https://github.com/devonfw/ide/blob/master/documentation/setup.asciidoc[setup] guide in the devon IDE documentation to learn where to download and how to setup the development environment.

== Usage
Please refer to the link:https://github.com/devonfw/ide/blob/master/documentation/usage.asciidoc[usage] section in the devon IDE documentation to learn about how to manage workspaces and create launch scripts.

== Commands
Please refer to the link:https://github.com/devonfw/ide/blob/master/documentation/cli.asciidoc[commandlets] section in the devon IDE documentation to learn more about the `devon` command and available sub-commands.

== Further Reading
To gain more insight into the motivation behind the devon IDE, you can read the link:https://github.com/devonfw/ide/blob/master/documentation/features.asciidoc[feature] section of the documentation.

//'''

//*Next Step:* link:jumpthequeue[JumpTheQueue Tutorial App]